# Generated by Django 3.0.7 on 2020-12-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=25),
            preserve_default=False,
        ),
    ]
