# Generated by Django 3.1.4 on 2021-01-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20201213_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
