# Generated by Django 3.1.4 on 2021-01-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_auto_20210123_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='deals_in',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Groceries', 'Groceries')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
