# Generated by Django 3.1.4 on 2021-01-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_contactmessage_deals_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='deals_in',
            field=models.CharField(max_length=200),
        ),
    ]
