# Generated by Django 3.1.4 on 2021-01-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_auto_20210123_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='assured_logo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
