# Generated by Django 3.1.4 on 2021-01-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_setting_assured_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='address',
            new_name='mail_address',
        ),
        migrations.AddField(
            model_name='setting',
            name='office_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
