# Generated by Django 3.1.4 on 2021-01-29 07:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_auto_20210124_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='privacy_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='t_n_c',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
