# Generated by Django 3.1.4 on 2021-02-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_auto_20210129_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='privacy_policy',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='t_n_c',
        ),
    ]
