# Generated by Django 3.1.4 on 2021-02-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_auto_20210202_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='deals_in',
        ),
    ]
