# Generated by Django 3.1.4 on 2021-01-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210105_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='key',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
    ]
