# Generated by Django 3.1.4 on 2021-01-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_wishlist_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
