# Generated by Django 3.1.4 on 2021-01-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210118_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daysadded',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
