# Generated by Django 3.1.4 on 2021-01-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20210119_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='daysadded',
        ),
        migrations.AddField(
            model_name='order',
            name='return_before_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('On Shipping', 'On Shipping'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Return Requested', 'Return Requested'), ('Returned', 'Returned')], default='New', max_length=50),
        ),
    ]
