# Generated by Django 3.0.7 on 2020-12-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_prevprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.TextField(),
        ),
    ]
