# Generated by Django 3.1.4 on 2021-01-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer',
            new_name='off',
        ),
    ]
