# Generated by Django 3.1.4 on 2021-01-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210116_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
