# Generated by Django 3.1.4 on 2021-01-16 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deals',
            field=models.CharField(choices=[('Deal of the day', 'Deal of the day'), ('Deal of the week', 'Deal of the week'), ('Deal of the month', 'Deal of the month')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='None', max_length=20),
        ),
    ]
