# Generated by Django 3.1.4 on 2021-01-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210117_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null='True', upload_to='Deals/')),
                ('deal', models.CharField(blank=True, choices=[('Deal of the day', 'Deal of the day'), ('Deal of the week', 'Deal of the week'), ('Deal of the month', 'Deal of the month')], max_length=25, null=True)),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField()),
            ],
        ),
    ]
