# Generated by Django 3.1.4 on 2021-01-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
