# Generated by Django 3.1.4 on 2021-01-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_deal_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='start',
            field=models.DateField(auto_now=True),
        ),
    ]
