# Generated by Django 3.1.4 on 2021-01-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_dealactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='onlyChar1',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='onlyChar2',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
