# Generated by Django 3.1.4 on 2021-01-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210117_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dealSlug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
