# Generated by Django 3.1.4 on 2021-01-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_dealslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='dealSlug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
