# Generated by Django 3.1.4 on 2021-01-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_deal_dealslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='featimage',
            field=models.ImageField(null=True, upload_to='Carousel/'),
        ),
        migrations.AddField(
            model_name='category',
            name='feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='minimum_Offer',
            field=models.IntegerField(default=0),
        ),
    ]
