# Generated by Django 3.1.4 on 2021-01-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20210118_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assured',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
