# Generated by Django 3.1.4 on 2021-01-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20210123_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
