# Generated by Django 3.1.4 on 2021-01-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_delete_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='feature',
            new_name='active',
        ),
        migrations.AddField(
            model_name='category',
            name='carousel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='special_deal',
            field=models.BooleanField(default=False),
        ),
    ]
