# Generated by Django 3.1.4 on 2021-01-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
