# Generated by Django 3.1.4 on 2021-01-28 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_feature_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.AddField(
            model_name='product',
            name='deal_ends',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='deals',
            field=models.CharField(choices=[('None', 'None'), ('Deal of the day', 'Deal of the day'), ('Deal of the week', 'Deal of the week'), ('Deal of the month', 'Deal of the month')], default='None', max_length=30),
        ),
    ]
