# Generated by Django 3.1.4 on 2021-01-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20210128_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featimage',
            field=models.ImageField(blank=True, null=True, upload_to='Carousel/'),
        ),
    ]
