# Generated by Django 3.1.4 on 2021-01-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20210129_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deal_ends',
            field=models.DateField(blank=True, null=True),
        ),
    ]
