# Generated by Django 3.1.4 on 2021-02-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20210201_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(null='True', upload_to='Deals/')),
                ('deal', models.CharField(blank=True, choices=[('Deal of the day', 'Deal of the day'), ('Deal of the week', 'Deal of the week'), ('Deal of the month', 'Deal of the month')], max_length=25, null=True)),
                ('onlyChar1', models.CharField(max_length=10, null=True, unique=True)),
                ('onlyChar2', models.CharField(max_length=10, null=True, unique=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('dealSlug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('show', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='Offers')),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='active',
            new_name='feature',
        ),
        migrations.RemoveField(
            model_name='category',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='category',
            name='special_deal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deal_ends',
        ),
        migrations.AlterField(
            model_name='category',
            name='featimage',
            field=models.ImageField(null=True, upload_to='Carousel/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deals',
            field=models.CharField(choices=[('Deal of the day', 'Deal of the day'), ('Deal of the week', 'Deal of the week'), ('Deal of the month', 'Deal of the month')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='product.category'),
        ),
    ]
